<a href="https://colab.research.google.com/github/yje0515/PythonStudy2025/blob/main/02_02_%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 02_01의 훈련세트와 테스트세트를 나누어 평가를 진행해 본 결과 문제가 발생한다
# 길이가 25cm, 무게가150g이면 사람이 판단했을 때는 도미인데 AI 는 빙어로 결론이 나온다
# 이 원인을 찾아보고 개선을 해보자.

# 전처리 데이터 앞쪽 35개는 도미(1), 뒷쪽 14개는 빙어(0) -> 총 49개의 데이터
# 도미(35개)와 빙어(14개) 데이터 49개
fish_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0,
                31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5, 34.0, 34.0, 34.5, 35.0,
                35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0, 9.8,
                10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]

fish_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0,
                500.0, 340.0, 600.0, 600.0, 700.0, 700.0, 610.0, 650.0, 575.0, 685.0, 620.0, 680.0,
                700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0, 6.7,
                7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

In [2]:
# 전에는 파이썬 리스트를 for문과 zip을 이용해서 배열로 만들었는데
# 넘파이에는 이 기능이 내장되어있는 메서드가 있다.
import numpy as np
np.column_stack(([1,2,3],[4,5,6])) # .column(열)_stack(쌓는다)
#                 길이용,무게용 -> 변환

array([[1, 4],
       [2, 5],
       [3, 6]])

In [3]:
fish_data = np.column_stack((fish_length,fish_weight))
# fish_data 변수에 2차원 배열을 넣는다 (길이,무게)
print(fish_data[:5]) # 데이터 5개 미리보기 (index 0~4)

[[ 25.4 242. ]
 [ 26.3 290. ]
 [ 26.5 340. ]
 [ 29.  363. ]
 [ 29.  430. ]]


In [5]:
# target 1 이면 도미, 0이면 빙어의 정답을 만들기
# 정답 파일을 생성한다
print(np.ones(5)) # 1로 채우기 테스트
print(np.zeros(10))# 0으로 채우기 테스트

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
fish_target = np.concatenate((np.ones(35),np.zeros(14)))
# .concatenate() 첫번째 차원을 따라 배열을 연결
# 1차원 배열(1이 35개 , 0이 14개) 도미35/빙어14
print(fish_target)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [8]:
from sklearn.model_selection import train_test_split
train_input,test_input, train_target,test_target = train_test_split(fish_data,fish_target,stratify=fish_target,random_state=42)

print(train_input.shape, test_input.shape) # 객체,특성
# train_input 훈련용 입력값
# test_input 테스트용 입력값
# train_target 훈련용 정답
# test_target 테스트용 정답
# stratify : 타겟값을 넣어줌(target의 class 비율을 유지한 채 데이터셋을 split함)
# random_state : 시드값을 42로 지정하고 랜덤적용(수업용)

# 결과 : 랜덤하게 처리하면서 훈련용(36객체, 2특성) 테스트용(13객체,2특성)

(36, 2) (13, 2)
